name: Deployment

on:
  push:
    branches:
      - staging

env:
  # Must match k8s deployment name
  DEPLOYMENT: community-detection-poc
  DEPLOYMENT_NAMESPACE: community-detection-poc
  DEPLOYMENT_URL: https://community-detection-poc.staging.dataesr.ovh/
  MM_NOTIFICATION_CHANNEL: bots

jobs:
  publish-ghcr:
    name: Publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: 🏁 Checkout
        uses: actions/checkout@v3

      - name: 🔑 Login Docker
        run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build client
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci --silent && npm run build --mode=production

      - name: 🐋 Build Docker image
        run: docker build -t ${{ github.repository }} .

      - name: 📦 Push Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag ${{ github.repository }} $IMAGE_ID:latest
          docker push $IMAGE_ID:latest

  deploy:
    name: Update staging deployment
    runs-on: ubuntu-latest
    needs: publish-ghcr
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Deploy to Cluster
        id: kubectl-deploy
        uses: dataesr/kubectl-deploy@v1.1
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DOAD_STAGING }}
        with:
          namespace: ${{ env.DEPLOYMENT_NAMESPACE }}
          restart: ${{ env.DEPLOYMENT }}

  notify:
    needs: deploy
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: dataesr/mm-notifier-action@v1
        with:
          deployment_url: ${{ env.DEPLOYMENT_URL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mattermost_channel: ${{ env.MM_NOTIFICATION_CHANNEL}}
          mattermost_webhook_url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
